

-- Bears Gov Overhaul - Mod ID -- c3ae4eb5-5416-4f70-820b-ac8ee33187e4



INSERT OR IGNORE INTO AiListTypes (ListType) VALUES
('RH_BEAR_GOV_PSEUDOS');
INSERT OR IGNORE INTO AiLists (ListType, LeaderType, System) VALUES
('RH_BEAR_GOV_PSEUDOS', 'MAJOR_CIV_DEFAULT_TRAIT', 'PseudoYields');
INSERT OR IGNORE INTO AiFavoredItems (ListType, Item, Favored, Value) VALUES
('RH_BEAR_GOV_PSEUDOS', 'PSEUDOYIELD_GOVERNOR', 		1, 300);



INSERT OR IGNORE INTO Modifiers  (ModifierId, ModifierType, SubjectRequirementSetId) VALUES		
		('RH_BEAR_PIONEER_MODIFIER',				'MODIFIER_PLAYER_ADJUST_DUPLICATE_FIRST_INFLUENCE_TOKEN',	'PLAYER_IS_AI');

INSERT OR IGNORE INTO ModifierArguments  (ModifierId, Name, Value) VALUES	
		('RH_BEAR_PIONEER_MODIFIER',						'Amount'   , 1);

INSERT INTO GovernorPromotionModifiers     (GovernorPromotionType,			ModifierId)   VALUES		
			('GOVERNOR_PROMOTION_BUILDER_GUILDMASTER',					'RH_BEAR_PIONEER_MODIFIER'),
			('GOVERNOR_PROMOTION_RESOURCE_MANAGER_SURPLUS_LOGISTICS',	'RH_BEAR_PIONEER_MODIFIER'),
			('GOVERNOR_PROMOTION_BEAR_RESETTLEMENT',					'RH_BEAR_PIONEER_MODIFIER'),
			('GOVERNOR_PROMOTION_MERCHANT_LAND_ACQUISITION',			'RH_BEAR_PIONEER_MODIFIER'),
			('GOVERNOR_PROMOTION_BEAR_URBAN_BOOM',						'RH_BEAR_PIONEER_MODIFIER'),
			('GOVERNOR_PROMOTION_BEAR_GOLD_RUSH',						'RH_BEAR_PIONEER_MODIFIER');
					


